project:
  type: website
  output-dir: docs
  # Optional: include extra static files at site root (uncomment if you add them)
  # resources:
  #   - keybase.txt
  #   - resume.pdf
  #   - cv.pdf

website:
  title: "Zachary Gooch"
  site-url: https://zacharygooch.com
  description: "Economics PhD student — research, teaching, and notes"

  open-graph:
    locale: en_US
  # Optional: show nice link cards on Twitter/X if you want
  # twitter-card:
  #   creator: "@your_handle"

  # Comments like Mike’s (Utterances) are optional; add when you have a blog/repo ready
  # comments:
  #   utterances:
  #     repo: Zach-Gooch/your-site-repo

  navbar:
    left:
      # NOTE: Use .qmd if these files live at the repo root.
      # If you move a page into a folder (e.g., research/index.qmd), then use just "research".
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Blog"
        href: blog.qmd

      # Icons (rightmost)
      - icon: github
        aria-label: GitHub
        href: https://github.com/Zach-Gooch
      - icon: rss
        aria-label: RSS
        href: blog.xml
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/zachary-r-gooch
      - icon: envelope
        aria-label: Email
        href: mailto:zg23a@fsu.edu

  page-footer:
    left: "© 2025 Zachary Gooch"
    right: "Built with Quarto"

format:
  html:
    theme: [pulse, _variables.scss]  
    css: styles.css
    toc: false
    toc-depth: 2
    anchor-sections: true

execute:
  freeze: auto
  
  
  
  
  
  
  
  